name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    strategy: 
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: env GOOS=windows GOARCH=amd64 go build -o build/

    - name: Test
      run: go test -v ./...
    
    - uses: actions/upload-artifact@v2
      with:
        name: test-artifact
        path: ./build
