name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    strategy: 
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        goos: [linux, darwin, windows]
        goarch: [amd64, amd64, amd64]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: env GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o output/

    - name: Test
      run: go test -v ./...
    
    - uses: actions/upload-artifact@v2
      with:
        name: test-artifact
        path: ./output
